name: appraisal_app
description: "Tactical firearm valuation terminal."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.10.5+9
  flutter_animate: ^4.5.0
  flex_color_scheme: ^8.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_functions: ^6.0.6
  firebase_storage: ^13.0.6
  camera_macos: ^0.0.9
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
